a = input('Digite algo: ')
print('[Você digitou: {}] - O seu tipo primitivo é? [{}]'.format(a, type(a)))
print('[Você digitou: {}] - Só tem espaço? [{}]'.format(a, a.isspace()))
print('[Você digitou: {}] - É um número? [{}]'.format(a, a.isnumeric()))
print('[Você digitou: {}] - É alfabetico? [{}]'.format(a, a.isalpha()))
print('[Você digitou: {}] - É alfanumérico? [{}]'.format(a, a.isalnum()))
print('[Você digitou: {}] - Está em maiúsculas? [{}]'.format(a, a.isupper()))
print('[Você digitou: {}] - Está em minúsculas: [{}]'.format(a, a.islower()))
print('[Você digitou: {}] - Está Capitalizada: [{}]'.format(a, a.istitle()))
