print('{:=^40}'.format(' TABUADA '))
from math import sqrt
n = int(input('Digite um numero: '))
print('=' * 40)
print('O numero digitado é: {}\nE a sua tabuada é a seguinte.'.format(n))
print('=' * 40)
print('{} x 01 = {} | Raiz quadrada = {:.2f}'.format(n, n*1, sqrt(n*1)))
print('{} x 02 = {} | Raiz quadrada = {:.2f}'.format(n, n*2, sqrt(n*2)))
print('{} x 03 = {} | Raiz quadrada = {:.2f}'.format(n, n*3, sqrt(n*3)))
print('{} x 04 = {} | Raiz quadrada = {:.2f}'.format(n, n*4, sqrt(n*4)))
print('{} x 05 = {} | Raiz quadrada = {:.2f}'.format(n, n*5, sqrt(n*5)))
print('{} x 06 = {} | Raiz quadrada = {:.2f}'.format(n, n*6, sqrt(n*6)))
print('{} x 07 = {} | Raiz quadrada = {:.2f}'.format(n, n*7, sqrt(n*7)))
print('{} x 08 = {} | Raiz quadrada = {:.2f}'.format(n, n*8, sqrt(n*8)))
print('{} x 09 = {} | Raiz quadrada = {:.2f}'.format(n, n*9, sqrt(n*9)))
print('{} x 10 = {} | Raiz quadrada = {:.2f}'.format(n, n*10, sqrt(n*10)))
print('{} x 11 = {} | Raiz quadrada = {:.2f}'.format(n, n*11, sqrt(n*11)))
print('{} x 12 = {} | Raiz quadrada = {:.2f}'.format(n, n*12, sqrt(n*12)))
print('=' * 40)
