nome = str(input('Digite o nome completo: ')).strip()
nome_dividido = nome.split()
total_char = nome.replace(' ','')
print('--------------------------------------------------')
print('Analisando o seu nome...')
print('1- Nome digitado: {}'.format(nome))
print('2- Nome em letras maiusculas: {}'.format(nome.upper().strip()))
print('3- Nome em letras minusculas: {}'.format(nome.lower()))
print('4- O nome digitadao tem {} caracteres (sem considerar os espacos).'.format(len(total_char)))
print('5- O seu primeiro nome é {} e tem {} caracteres.'.format(nome_dividido[0], len(nome_dividido[0])))
print('\n---------------------- Outra forma ----------------------')
print('O seu nome ao todo tem {} letras'.format(len(nome) - nome.count(' ')))
print('O seu primeiro nome tem {} letras'.format(nome.find(' ')))
