#Manipula de Texto
frase = 'Curso em Video Python'
print(frase)
print('--------------------------')
print(frase.upper().count('O'))
print('--------------------------')
print('Comprimento da String: ', len(frase))
print('--------------------------')
print('Substitui a palavra Python por Java: ', frase.replace('Python', 'Java'))
print('--------------------------')
print(frase[10])
print('--------------------------')
frase = frase.replace('Python', 'Android')
print(frase)
print('--------------------------')
print(frase.find('Video'))
print('--------------------------')
dividido = frase.split()
print(dividido)
print(dividido[0][0])
